version: "3.8"
services:
  micro_service:
    container_name: microservice
    build: .
    expose:
      - 8000
    command: bash -c "cd /app && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./microservice:/app
    ports:
      - 8000:8000
    restart: always